In [1]:
import numpy as np

In [2]:
# generating a one dimensional arry 1-d
np.zeros(3, dtype=np.int16)

array([0, 0, 0], dtype=int16)

In [3]:
# generating a two or n dimensional array 
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
np.zeros(shape=(2,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [5]:
#generating any array with arange method
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,19, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [7]:
np.arange(start=10,stop=17,step=2)

array([10, 12, 14, 16])

In [8]:
# generating any array of intervale data 
np.linspace(3, 4, 10)

array([3.        , 3.11111111, 3.22222222, 3.33333333, 3.44444444,
       3.55555556, 3.66666667, 3.77777778, 3.88888889, 4.        ])

In [9]:
np.linspace(start=2, stop=10, num=7)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [10]:
# Generating a identity matrix 

np.eye(4, dtype=np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [11]:
# generating any array of ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.random.rand(4)

array([0.03882927, 0.34819128, 0.93790776, 0.26729537])

In [13]:
np.random.randn(6)

array([-0.71804385,  0.0234081 , -1.53040799,  0.38935234,  1.78743141,
       -1.00106728])

In [14]:
np.random.randint(5,10, 19)

array([9, 9, 8, 9, 6, 6, 9, 5, 8, 8, 8, 7, 7, 6, 9, 7, 7, 5, 8])

### Rasheping arry

In [15]:
arr = np.arange(25)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr = arr.reshape(5,5)
arr[1,:] = arr[1,:] * 0

In [18]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr[3, :] *= 0

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14],
       [ 0,  0,  0,  0,  0],
       [20, 21, 22, 23, 24]])

In [21]:
ranarr = np.random.randint(10, 100, 10)

In [22]:
ranarr

array([80, 74, 54, 36, 77, 33, 10, 17, 36, 28])

In [23]:
ranarr.max()

80

In [24]:
ranarr.min()

10

In [25]:
ranarr.mean()

44.5

In [26]:
ranarr.argmax()

0

In [27]:
ranarr.argmin()

6

In [28]:
ranarr.shape

(10,)

In [29]:
ranarr = ranarr.reshape(5,2)

In [30]:
ranarr.shape

(5, 2)

In [31]:
ranarr.dtype

dtype('int64')

### Array indexing

In [32]:
array = np.arange(0, 11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
array[:5] = 23
array

array([23, 23, 23, 23, 23,  5,  6,  7,  8,  9, 10])

In [48]:
array.any()

SyntaxError: invalid syntax (296653137.py, line 1)

In [34]:
array_copy = array.copy()
array_copy[:] = 0

In [35]:
array_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# array

In [38]:
array_copy.shape

(11,)

In [39]:
array.shape

(11,)

In [40]:
arr_1 = np.array([[12, 34, 45], [20, 34, 11], [11, 29, 78]])
arr_1

array([[12, 34, 45],
       [20, 34, 11],
       [11, 29, 78]])

In [41]:
arr_1[1:,:]

array([[20, 34, 11],
       [11, 29, 78]])

In [42]:
arr_1[1:, 1:]

array([[34, 11],
       [29, 78]])

In [49]:
array_2d = np.arange(50).reshape(5,10)

In [50]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
array_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [51]:
array_2d[array_2d>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])